# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc48741ee3560b55c89c83ad294df27490d2f8797d11060e9ab5b37bb7277ad728a247e2ebf93acee72f5163919f7653e2dc9367e23399df43a5d3a676bd1d26

test:
  secret_key_base: 5cecc8eea47b4e6ccc9bda4343309908a5f50754a396e0e00f97f6f95d2ec42dc336dda22c72c0abebdb4195847e84333270a6691e99dae10580ede397ae71d6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
